application: pgweb-193811
version: 1
runtime: python27
api_version: 1
threadsafe: true
automatic_scaling:
  max_idle_instances: 2 
  
handlers:
- url: /
  static_files: www/index.html
  upload: www/index.html
  
- url: /(.*)
  static_files: www/\1
  upload: www/(.*) 